<?php

// Compression level for PNG mockups generated by convert_webp_to_png_server().
// 0 = no compression, 9 = maximum compression.
// Higher values produce smaller files but require more CPU time.
if (!defined('PNG_COMPRESSION_LEVEL')) {
    define('PNG_COMPRESSION_LEVEL', 7);
}

function customiizer_log($message) {
        $log_file = __DIR__ . '/customiizer.log';
        $date = date('Y-m-d H:i:s');
        $line = "[$date] $message\n";
        file_put_contents($log_file, $line, FILE_APPEND);
}
