<?php

// Compression level for PNG mockups generated by convert_webp_to_png_server().
// 0 = no compression, 9 = maximum compression.
// Higher values produce smaller files but require more CPU time.
if (!defined('PNG_COMPRESSION_LEVEL')) {
    define('PNG_COMPRESSION_LEVEL', 8);
}

// Maximum width or height for PNG mockups generated for Printful.
// Images larger than this size are downscaled before saving.
if (!defined('MOCKUP_MAX_DIMENSION')) {
    define('MOCKUP_MAX_DIMENSION', 1500);
}

// Hosts allowed for remote image downloads performed by convert_webp_to_png_server().
// Only images from these domains will be retrieved.
if (!defined('ALLOWED_IMAGE_HOSTS')) {
    $host = parse_url(site_url(), PHP_URL_HOST);
    $hosts = ['customiizer.blob.core.windows.net'];
    if ($host && !in_array($host, $hosts, true)) {
        $hosts[] = $host;
    }
    define('ALLOWED_IMAGE_HOSTS', $hosts);
}

// Timeout for remote image downloads in seconds.
if (!defined('REMOTE_IMAGE_TIMEOUT')) {
    define('REMOTE_IMAGE_TIMEOUT', 10);
}

// Maximum bytes allowed for a downloaded image (5 MB by default).
if (!defined('REMOTE_IMAGE_MAX_BYTES')) {
    define('REMOTE_IMAGE_MAX_BYTES', 5 * 1024 * 1024);
}

function customiizer_log($message) {
        $log_file = __DIR__ . '/customiizer.log';
        $date = date('Y-m-d H:i:s');
        $line = "[$date] $message\n";
        file_put_contents($log_file, $line, FILE_APPEND);
}
